name: newsapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.3
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  get: ^4.6.6
  cached_network_image: ^3.3.1


  cupertino_icons: ^1.0.2
  timeago: ^3.6.1
  skeletonizer: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/placeholder.png
    - assets/error_placeholder.png

  
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Regular.ttf
          weight: 400
        - asset: fonts/Lexend-Regular.ttf
          weight: 700
        - asset: fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: fonts/Lexend-Black.ttf
          weight: 200
        - asset: fonts/Lexend-ExtraLight.ttf
          weight: 300
        - asset: fonts/Lexend-Light.ttf
          weight: 500
        - asset: fonts/Lexend-Medium.ttf
          weight: 600
        - asset: fonts/Lexend-Medium.ttf


